name: 🔄 Sync with Upstream

on:
  workflow_dispatch:

jobs:
  sync_with_upstream:
    name: 🔄 Sync main with upstream latest
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: 🚚 Checkout target repo
        uses: actions/checkout@v4

      - name: 🔄 Sync Upstream
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4
        with:
          upstream_sync_repo: idinging/freemail
          upstream_sync_branch: master
          target_sync_branch: master
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}
          test_mode: false

      - name: ❌ 通知同步失败 / Check for Failure
        if: failure()
        run: |
          echo "❌ 同步失败！通常是因为 wrangler.toml 与上游产生了冲突。"
          echo "请手动解决冲突后再同步。"
